#!/usr/bin/env python3
"""Copy a knowledge-only skill into a client discovery directory.

Does not install Claude plugin hooks, grant permissions, or edit client settings.
For the full Claude plugin use the marketplace instructions in README.md.

Every installation records INSTALL_PROVENANCE.json: the source version and
commit, the installer version, and a SHA-256 digest of each installed file.
Replacing an installation that differs from its manifest, or that has no
manifest, requires --force --discard-local-changes. The manifest is a snapshot
for detecting accidental or local drift; it is not a signed attestation.
"""

import argparse
from contextlib import contextmanager
from datetime import datetime, timezone
import fnmatch
import hashlib
import json
import os
from pathlib import Path
import shutil
import stat
import subprocess
import sys
import tempfile

sys.path.insert(0, str(Path(__file__).resolve().parent))
import validate_skill as vs  # noqa: E402

INSTALLER_VERSION = '0.2.0'
NAME = 'ros2-engineering-skills'
PROVENANCE = 'INSTALL_PROVENANCE.json'
PROVENANCE_SCHEMA = 1
HASH_ALGORITHM = 'sha256'
CLIENT_DIRS = {'portable': '.agents', 'codex': '.agents', 'claude': '.claude',
               'cursor': '.cursor', 'gemini': '.gemini'}
BUNDLE = ('SKILL.md', 'LICENSE', 'README.md', 'requirements.txt',
          'references', 'scripts', 'agents', 'docs', 'evals', 'examples',
          'CONTRIBUTING.md', 'SECURITY.md', 'ROADMAP.md', 'CHANGELOG.md')
# Never copied and never recorded in the manifest.
COPY_IGNORES = ('__pycache__', '*.pyc', '.pytest_cache', '.coverage', '.DS_Store')
# Generated by running tools inside an installation; not a local edit.
DRIFT_IGNORES = COPY_IGNORES + ('.mypy_cache', '.hypothesis', 'coverage.xml', 'htmlcov')
DISCARD_HINT = 're-run with --force --discard-local-changes to replace it'


def destination(client, project=None, home=None):
    base = Path(project) if project is not None else Path(home or Path.home())
    return base / CLIENT_DIRS[client] / 'skills' / NAME


def check_target(target, force):
    """Rechecked under the installer lock, before changing an existing target."""
    if target.is_symlink():
        raise ValueError('Refusing to replace a symlink; remove it explicitly first')
    if target.exists():
        if not force:
            raise ValueError('Target exists; use --force to replace a skill installation')
        if not target.is_dir() or not (target / 'SKILL.md').is_file():
            raise ValueError('Refusing to replace a target that is not a skill installation')


@contextmanager
def install_lock(parent):
    lock = parent / ('.' + NAME + '.install-lock')
    try:
        lock.mkdir(mode=0o700)
    except FileExistsError as exc:
        raise ValueError('Another installation or stale lock exists: ' + str(lock)) from exc
    try:
        yield
    finally:
        lock.rmdir()


# ------------------------------------------------------------------ provenance

def ignored(parts, patterns):
    return any(fnmatch.fnmatch(part, pattern) for part in parts for pattern in patterns)


def sha256_file(path):
    digest = hashlib.sha256()
    with open(path, 'rb') as handle:
        for chunk in iter(lambda: handle.read(1 << 16), b''):
            digest.update(chunk)
    return digest.hexdigest()


def file_digests(root, patterns):
    """Hash regular files under root without following symlinks.

    Returns (digests, symlinks, other). A symlink is listed and never opened, so
    a link added to an installation cannot make this scanner read files outside
    it. Sockets, FIFOs, and devices are listed under ``other``.
    """
    root = Path(root)
    digests, symlinks, other = {}, [], []

    def walk(directory):
        with os.scandir(directory) as entries:
            listing = sorted(entries, key=lambda entry: entry.name)
        for entry in listing:
            path = Path(entry.path)
            parts = path.relative_to(root).parts
            relative = '/'.join(parts)
            if relative == PROVENANCE or ignored(parts, patterns):
                continue
            if entry.is_symlink():
                symlinks.append(relative)
                continue
            mode = entry.stat(follow_symlinks=False).st_mode
            if stat.S_ISDIR(mode):
                walk(path)
            elif stat.S_ISREG(mode):
                digests[relative] = sha256_file(path)
            else:
                other.append(relative)

    walk(root)
    return dict(sorted(digests.items())), symlinks, other


def source_version(source):
    try:
        meta = vs.skill_frontmatter(Path(source) / 'SKILL.md')
    except ValueError as exc:
        raise ValueError('Source bundle failed validation: ' + str(exc)) from exc
    custom = meta.get('metadata')
    version = custom.get('version') if isinstance(custom, dict) else None
    if not isinstance(version, str) or not version.strip():
        raise ValueError('Source bundle has no version')
    return version


def source_commit(source):
    """Return (commit, dirty) for a Git checkout, or (None, None) when unknown.

    ``dirty`` only considers the paths that are installed (BUNDLE), so edits to
    tests or CI configuration in the checkout do not mark the bundle dirty.
    """
    try:
        head = subprocess.run(['git', '-C', str(source), 'rev-parse', 'HEAD'],
                              capture_output=True, text=True, timeout=20)
        if head.returncode != 0:
            return None, None
        status = subprocess.run(['git', '-C', str(source), 'status', '--porcelain', '--', *BUNDLE],
                                capture_output=True, text=True, timeout=20)
    except (OSError, subprocess.SubprocessError):
        return None, None
    commit = str(head.stdout).strip()
    if len(commit) != 40 or status.returncode != 0:
        return None, None
    return commit, bool(str(status.stdout).strip())


def write_provenance(staging, source):
    digests, symlinks, other = file_digests(staging, COPY_IGNORES)
    if symlinks or other:
        raise ValueError('Staged bundle contains symlinks or special files: '
                         + ', '.join(symlinks + other))
    commit, dirty = source_commit(source)
    manifest = {
        'schema_version': PROVENANCE_SCHEMA,
        'hash_algorithm': HASH_ALGORITHM,
        'skill_name': NAME,
        'source_version': source_version(source),
        'source_commit': commit,
        'source_dirty': dirty,
        'installer': 'scripts/install_skill.py',
        'installer_version': INSTALLER_VERSION,
        'layout': 'knowledge-only',
        'installed_at': datetime.now(timezone.utc).replace(microsecond=0)
        .isoformat().replace('+00:00', 'Z'),
        'files': digests,
    }
    (Path(staging) / PROVENANCE).write_text(json.dumps(manifest, indent=2) + '\n', encoding='utf-8')
    return manifest


def load_provenance(target):
    """Return (manifest, None) or (None, reason) without following symlinks."""
    path = Path(target) / PROVENANCE
    if path.is_symlink():
        return None, 'provenance manifest is a symlink'
    if not path.is_file():
        return None, 'no provenance manifest'
    try:
        manifest = json.loads(path.read_text(encoding='utf-8'))
    except (OSError, ValueError) as exc:
        return None, 'unreadable provenance manifest: ' + str(exc)
    if not isinstance(manifest, dict):
        return None, 'provenance manifest is not an object'
    if manifest.get('schema_version') != PROVENANCE_SCHEMA:
        return None, 'unsupported provenance schema: ' + repr(manifest.get('schema_version'))
    if manifest.get('hash_algorithm') != HASH_ALGORITHM:
        return None, 'unsupported hash algorithm: ' + repr(manifest.get('hash_algorithm'))
    files = manifest.get('files')
    if not isinstance(files, dict) or not all(
        isinstance(k, str) and isinstance(v, str) for k, v in files.items()
    ):
        return None, 'provenance file table is malformed'
    return manifest, None


def drift_report(target):
    """Compare an installation with its manifest. Never follows symlinks."""
    target = Path(target)
    report = {'target': str(target)}
    if target.is_symlink():
        report.update(status='unverified', reason='target is a symlink')
        return report
    if not target.is_dir():
        report.update(status='unverified', reason='target does not exist')
        return report
    manifest, reason = load_provenance(target)
    if manifest is None:
        report.update(status='unverified', reason=reason)
        return report
    digests, symlinks, other = file_digests(target, DRIFT_IGNORES)
    recorded = manifest['files']
    modified = sorted(p for p in recorded if p in digests and digests[p] != recorded[p])
    missing = sorted(p for p in recorded if p not in digests)
    added = sorted(p for p in digests if p not in recorded)
    drifted = bool(modified or missing or added or symlinks or other)
    report.update(
        status='drifted' if drifted else 'clean',
        source_version=manifest.get('source_version'),
        source_commit=manifest.get('source_commit'),
        source_dirty=manifest.get('source_dirty'),
        installer_version=manifest.get('installer_version'),
        installed_at=manifest.get('installed_at'),
        modified=modified, missing=missing, added=added, symlinks=symlinks, other=other,
    )
    return report


def refuse_drift(target, discard):
    """Refuse to replace an installation unless it is clean or discard is set."""
    report = drift_report(target)
    if report['status'] == 'clean' or discard:
        return report
    if report['status'] == 'unverified':
        raise ValueError('Installed skill cannot be verified (' + report['reason']
                         + '); local edits may be lost; ' + DISCARD_HINT)
    details = '; '.join(key + ': ' + ', '.join(report[key])
                        for key in ('modified', 'missing', 'added', 'symlinks', 'other')
                        if report[key])
    raise ValueError('Installed skill differs from its provenance manifest ('
                     + details + '); ' + DISCARD_HINT)


# --------------------------------------------------------------------- install

def install(source, target, force=False, dry_run=False, discard_local_changes=False):
    source = Path(source).resolve()
    target = Path(target).expanduser().absolute()
    resolved = target.resolve()
    if (target.name != NAME or resolved == source
            or resolved.is_relative_to(source) or source.is_relative_to(resolved)):
        raise ValueError('Target must be a separate skill directory named ' + NAME)
    check_target(target, force)
    if force and target.exists():
        refuse_drift(target, discard_local_changes)
    for relative in BUNDLE:
        entry = source / relative
        if not entry.exists():
            raise ValueError('Incomplete source bundle: ' + relative)
        candidates = [entry, *entry.rglob('*')] if entry.is_dir() else [entry]
        if any(item.is_symlink() for item in candidates):
            raise ValueError('Copy installation requires a bundle without nested symlinks')
    if dry_run:
        return {'status': 'dry-run', 'target': str(target), 'layout': 'knowledge-only',
                'files': list(BUNDLE), 'provenance': PROVENANCE}
    target.parent.mkdir(parents=True, exist_ok=True)
    # Validate in a sibling staging directory before touching an existing install.
    # Backup rename allows restoration if the final rename fails.
    with install_lock(target.parent), tempfile.TemporaryDirectory(prefix='.skill-install-', dir=target.parent) as tmp:
        check_target(target, force)
        if force and target.exists():
            refuse_drift(target, discard_local_changes)
        staging = Path(tmp) / NAME
        staging.mkdir()
        for relative in BUNDLE:
            entry, dest = source / relative, staging / relative
            if entry.is_dir():
                shutil.copytree(entry, dest, ignore=shutil.ignore_patterns(*COPY_IGNORES))
            else:
                shutil.copy2(entry, dest)
        # The manifest is part of the installation, so the validator sees the
        # final staged tree including it.
        manifest = write_provenance(staging, source)
        validator = source / 'scripts/validate_skill.py'
        result = subprocess.run(
            [sys.executable, str(validator), '--root', str(staging), '--installed', '--portable'],
            text=True, capture_output=True, timeout=20,
        )
        if result.returncode != 0:
            raise ValueError('Staged skill failed validation: ' + result.stdout + result.stderr)
        report = json.loads(result.stdout)
        if not isinstance(report, dict) or report.get('status') != 'pass':
            raise ValueError('Staged skill failed validation: unrecognized report')
        # Keep the backup OUTSIDE TemporaryDirectory. If final rename and
        # rollback both fail, automatic staging cleanup must never erase it.
        backup_root = None
        backup = None
        if target.exists():
            backup_root = Path(tempfile.mkdtemp(prefix='.skill-backup-', dir=target.parent))
            backup = backup_root / 'previous'
            try:
                target.rename(backup)
            except OSError:
                backup_root.rmdir()
                raise
        try:
            staging.rename(target)
        except OSError as install_error:
            if backup is not None:
                try:
                    backup.rename(target)
                except OSError as restore_error:
                    raise OSError('Installation and rollback failed; previous installation '
                                  f'preserved at {backup}: {restore_error}') from install_error
                backup_root.rmdir()
            raise
        retained_backup = None
        if backup_root is not None:
            try:
                shutil.rmtree(backup_root)
            except OSError:
                # Installation succeeded; a cleanup failure is not a rollback.
                retained_backup = str(backup_root)
    report = {'status': 'installed', 'target': str(target), 'layout': 'knowledge-only',
              'hooks_installed': False, 'provenance': PROVENANCE,
              'source_version': manifest['source_version'],
              'source_commit': manifest['source_commit'],
              'installer_version': INSTALLER_VERSION}
    if retained_backup is not None:
        report['backup_retained'] = retained_backup
    return report


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--version', action='version', version=INSTALLER_VERSION)
    parser.add_argument('--client', choices=tuple(CLIENT_DIRS), default='portable')
    parser.add_argument('--project', type=Path, help='project root; omitted means user scope')
    parser.add_argument('--target', type=Path, help='explicit final skill directory')
    parser.add_argument('--force', action='store_true')
    parser.add_argument('--discard-local-changes', action='store_true',
                        help='with --force: replace an installation that differs from its '
                             'provenance manifest or has none')
    parser.add_argument('--dry-run', action='store_true')
    parser.add_argument('--verify', action='store_true',
                        help='report drift between an installation and its provenance '
                             'manifest; exit 0 only when clean')
    args = parser.parse_args(argv)
    if args.target and args.project:
        parser.error('--target and --project are mutually exclusive')
    if args.discard_local_changes and not args.force:
        parser.error('--discard-local-changes requires --force')
    if args.verify and (args.force or args.dry_run or args.discard_local_changes):
        parser.error('--verify cannot be combined with --force, --dry-run, or --discard-local-changes')
    target = args.target or destination(args.client, args.project)
    try:
        if args.verify:
            result = drift_report(Path(target).expanduser().absolute())
            print(json.dumps(result, indent=2))
            return int(result['status'] != 'clean')
        result = install(Path(__file__).resolve().parents[1], target, args.force, args.dry_run,
                         args.discard_local_changes)
    except (OSError, ValueError, subprocess.SubprocessError) as exc:
        print(json.dumps({'status': 'error', 'error': str(exc)}))
        return 1
    print(json.dumps(result, indent=2))
    return 0


if __name__ == '__main__':
    sys.exit(main())
